### ISSUE TITLE
Session::abort called after we are authenticated

### ISSUE THREAD

**Issue by adamlc** [voryx/Thruway#110] opened 2015-06-16 13:13 UTC
I've just gone in to production with Thruway, all is going well do far! Just having a weird error!

I'm getting the error "Session::abort called after we are authenticated". Tracing it back on onMessage in Thruway\Peer\Router the message the client is sending is a Goodbye message, but for some reason the session has a realm of null. When that happens Thruway throws a wamp.error.unknown and thats when the error is thrown. This seems to be effecting some (not all) autobahn clients.

I'm not sure how this could happen? I've not really had time to do any more investigation yet. Could it be someone who is quickly connecting then disconnecting before the session has been setup?

**Comment by mbonneau** [comment] 2015-06-16 13:52
What version of Thruway are you using?

**Comment by adamlc** [comment] 2015-06-16 13:53
Sorry should have said, 0.3.7 :)

**Comment by davidwdan** [comment] 2015-06-16 15:55
I'm going to take a look at this issue.  Is this where you traced the it to in `onMessage`?

https://github.com/voryx/Thruway/blob/0.3.7/src/Thruway/Peer/Router.php#L137

**Comment by adamlc** [comment] 2015-06-17 07:20
Hi @davidwdan yes thats where I traced the issue back to. Thanks for your help!

**Comment by davidwdan** [comment] 2015-06-17 14:37
I'm wondering if the router is somehow receiving 2 Goodbye messages.

I took a look at JumpLead (which looks very nice, btw) and I noticed that you are also using a long polling transport.  Since Thruway doesn't directly support long polling, I'm assuming you're using some sort of proxy.

Do you know if this error occurs on both transports or just one?

**Comment by adamlc** [comment] 2015-06-17 14:47
@davidwdan I've actually build the long polling transport myself. I was going to share it with the community when I've tidied it up a bit!

The error seems to be originating from the Ratchet transport:

```[Thruway\Transport\RatchetTransportProvider 1] Exception occurred during onMessage: Session::abort called after we are authenticated [] []```

Saying there we're getting a fair few of these errors too, but it doesn't look like this is fully implemented in Thruway yet looking at the code:

```[Thruway\Transport\RatchetTransportProvider 1] onError... [] []```

If you want me to add some debugging stuff in let me know! I've not investigated what the onError's are in the RatchetTransportProvider. I wasn't sure if they were directly related.

**Comment by davidwdan** [comment] 2015-06-17 15:51
`onClose` is called after the error is emitted, so it should be cleaning up properly.  I'm not sure if it's related or not, but I would like to see what the onError exception message is.

Can you get a copy of the raw GoodBye message?

**Comment by adamlc** [comment] 2015-06-18 07:11
Ill add some more debug code in and see if I can figure it out.

Unfortunately I can't replicate the issue my end, the errors seem to be coming from other users connected though Jumplead. I'll see what I can do to capture some more information for you :)

**Comment by adamlc** [comment] 2015-06-18 07:38
As regards the the Goodbye message, I just added some logging:

```php
            } else {
                Logger::error($this, "Unknown error: " . json_encode($msg));
                $session->abort(new \stdClass(), "wamp.error.unknown");
            }
```

and now I've been starting to get some errors coming in:
```bash
[2015-06-18 07:32:52] alfred.ERROR: [Thruway\Peer\Router 1] Unknown error: [6,{},"wamp.close.normal"] [] []
[2015-06-18 07:33:01] alfred.ERROR: [Thruway\Peer\Router 1] Unknown error: [6,{},"wamp.close.normal"] [] []
[2015-06-18 07:33:58] alfred.ERROR: [Thruway\Peer\Router 1] Unknown error: [6,{},"wamp.close.normal"] [] []
[2015-06-18 07:35:28] alfred.ERROR: [Thruway\Peer\Router 1] Unknown error: [6,{},"wamp.close.normal"] [] []
[2015-06-18 07:35:59] alfred.ERROR: [Thruway\Peer\Router 1] Unknown error: [6,{},"wamp.close.normal"] [] []
```

They seem to look like normal goodbye's but they dont have a realm for some reason?

**Comment by adamlc** [comment] 2015-06-18 08:14
Also did the same for the onError in RatchetTransport:

```[2015-06-18 08:07:01] alfred.ERROR: [Thruway\Transport\RatchetTransportProvider 1] Socket Error: Tried to write to closed stream. [] []```

Thats only happened once. So its likely the 2 aren't related.

**Comment by mbonneau** [comment] 2015-06-18 14:12
Hi @adamlc 

I have been tracing through the source to try and figure out how this is happening and I am still coming up empty. Right now the only possibility I can think of is that the Goodbye message is being sent before a Hello message. 

In looking through the AutobahnJS sources, it looks like that is not possible from that end.

Is your long-polling transport a proxy that connects using a websocket or is it an actual transport provider?

To debug further I could have the router log with the session ids as they are created and show which messages are coming from and being sent to each so that we can trace it by session. Just let me know and I will create a branch for that.

**Comment by adamlc** [comment] 2015-06-18 14:29
Hi @mbonneau the long polling is an actual transport.

There is one possibility, so that the server runs over WSS I use stunnel. I guess its possible that stunnel could be doing something funky!

Also, I'm using your dev-pong branch as I'm pinging clients to check they are alive too. I was getting this behaviour before I added that so I'm pretty sure thats not the issue either.

Is there a nice way of logging the router log at the moment?

**Comment by mbonneau** [comment] 2015-06-18 14:59
I can't think of a "nice" way.

There are a couple things that would be helpful in debugging, but I am not sure how feasible they are:

You could add more logging so you can trace sessions like this: https://github.com/mbonneau/Thruway/commit/5ed31c5525ac91b73c34646ee104718e9a5337d3

Or, if the traffic is not too high and it is not too burdensome, you could capture the network traffic in between stunnel and Thruway so that you can trace back what is going on.

**Comment by adamlc** [comment] 2015-06-18 15:10
I'll have a stab at this tomorrow as I'm due to go home shortly.

There are a few hundred people connected at the moment so there might be a lot of data to log! I'm using monolog so I'll setup something separate to write it all to a text file or something.

I'll see what I can do about logging data between stunnel and get back to you.

**Comment by adamlc** [comment] 2015-06-19 10:39
Well this is interesting! Looks like the client is sending the Goodbye message more than once!

```bash
[Thruway\Peer\Router 1] (8619810019870767) New Session started {"type":"ratchet","transportAddress":"172.17.0.68"} [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [1,"jumplead",{"roles":{"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"progressive_call_results":true}},"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"publisher_identification":true}},"subscriber":{"features":{"publisher_identification":true}}},"authmethods":["jwt"]}] [] []
[Thruway\Session 1] (8619810019870767) To Client: [4,"jwt",{"challenge":{},"challenge_method":"jwt"}] [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [5,"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRfaWQiOjE2NzUsInZpc2l0b3JfaWQiOiI1NTgzZGU0MDJmYzViYjEwMTc4YjQ1NjgiLCJleHAiOjE0MzQ3MTI2NzIsImxvYyI6eyJsYXQiOjIwLCJsbmciOjc3fX0.x_9-3694er4lutr0gsuukE5qddTM0kGMYuwIRAf6HnM",{}] [] []
[Thruway\Session 1] (8619810019870767) To Client: [2,8619810019870767,{"authid":"{\"client_id\":1675,\"visitor_id\":\"5583de402fc5bb10178b4568\",\"exp\":1434712672,\"loc\":{\"lat\":20,\"lng\":77}}","authroles":["jumplead_visitor_5583de402fc5bb10178b4568","authenticated_user"],"authrole":"jumplead_visitor_5583de402fc5bb10178b4568","roles":{"broker":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true,"subscriber_metaevents":true}},"dealer":{"features":{"caller_identification":true,"progressive_call_results":true}}}}] [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [32,423125357732869,{},"com.jumplead.client.1675.private.5583de402fc5bb10178b4568"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [33,423125357732869,5970904786412713] [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [6,{},"wamp.error.goodbye_and_out"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is jumplead [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Peer\Router 1] (8619810019870767) From Client: Thruway\Transport\RatchetTransport: [6,{},"wamp.close.normal"] [] []
[Thruway\Session 1] (8619810019870767) To Client: [3,{},"wamp.error.unknown"] [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
[Thruway\Session 1] (8619810019870767) onClose: realm is [] []
```

Looks like Thruway is doing whats its supposed to do and then the client carries on sending goodbye messages? 

I guess it might be down to the client (autobahn), the transport (ratchet) or the SSL proxy (stunnel)? 

If the issue is related stunnel then I'm not sure how to log the data for that. Although it seems pretty odd that it works 99% of the time.

Any thoughts guys?

**Comment by mbonneau** [comment] 2015-06-19 13:38
I was able to reproduce the results by calling ```connection.close()``` repeatedly in AuthobahnJS.

```
connection.close();
connection.close();
connection.close();
connection.close();
```

I haven't been able to get it to happen every time because I think there are some network timing issues that help bring it out and I am testing on my local system.

What I think is happening is that multiple goodbye messages get put into the receive buffer before the first one is even processed by ```Realm::onMessage```.

The shutdown occurs with the first message, but there are still a few messages left in the buffer and the transport continues to try to feed them to the router which, at this point, has no realm associated with the session.

To remedy this, we should probably stop processing messages once we have shutdown (seems obvious). Also, I am thinking that AutobahnJS probably should not send goodbye after it has already sent goodbye once, but I don't think that is a big issue.

Do you think it is possible that close is being called multiple times on the client side?

**Comment by adamlc** [comment] 2015-06-19 13:48
I guess its possible. I remember we had a bug with firefox where we needed something like this to get round it:

```javascript
$(window).on('beforeunload', function(){
    connection.close();
});
```

That code might be called more than once I suppose, the only time I think that might possible is if the page has iframes or something thats firing the code when each one closes? Not sure. I could quite easily put something in to check if its already closed or not.

I guess there seems to be several issues here. It would definitely make sense to stop processing messages once the connection is closed. That might also fix the other error I'm having (```[Thruway\Transport\RatchetTransportProvider 1] Socket Error: Tried to write to closed stream. [] []```).

**Comment by mbonneau** [comment] 2015-07-20 18:33
This issues seems to be a function of the client incorrectly sending multiple goodbye messages - which does output warnings. I am closing thing issue but feel free to reopen if you think there needs to be more discussion.

**Closed by mbonneau** 2015-07-20 18:33 UTC

**Comment by adamlc** [comment] 2015-07-22 08:48
@mbonneau I appreciate this is probably a client issue. Theres quite a lot of these errors, our error reporting has caught 5600 errors in the past 6 weeks so its pretty common for us at least!

Do you think we should bring this up with Autobahn?
