### ISSUE TITLE
Use non-deprecated / abandoned version of Guzzle

### ISSUE THREAD

**Issue by J7mbo** [voryx/Thruway#242] opened 2017-04-19 13:48 UTC
A base install through running `composer require voryx/Thruway` yields the warning:

> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by davidwdan** [comment] 2017-04-19 13:54
This is a duplicate of #189

**Closed by davidwdan** 2017-04-19 13:54 UTC
